.TH instantsearch 1 instantSEARCH
.SH NAME
instantSEARCH \- simple file search UI using plocate
.SH SYNOPSIS
.B instantsearch
.RB [ \-H ]
.SH DESCRIPTION
Opens an a searchbox that can search through all files on your file system and
provides a quick way of performing various actions on the search results. 

.SH OPTIONS
.TP
.B \-H
Checks the health of all all required prerequisites for instantSEARCH
